"""add cascade delete-orphan to AdminUsageLogs relationship

Revision ID: 8235c0ec13b5
Revises: 9fa4831e991a
Create Date: 2025-09-25 19:16:18.058208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8235c0ec13b5'
down_revision = '9fa4831e991a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
